remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap
github: [metadata]
name: Elfriede Steil-Schächinger
title: Heilkundepraxis Elfriede Steil-Schächinger
subtitle: Heilpraktikerin & Physiotherapeutin
locale: de
repository: schaechinger/heilkundepraxis-steil
title_separator: "|"
date_format: "%d.%m.%Y"
timezone: Europe/Berlin
future: true

logo: /assets/images/icon.png
include: ["_pages"]

collections:
  discourses:
    output: true
    permalink: /vortraege/:year-:month-:day-:title
  services:
    output: true
    permalink: /leistungen/:path/

masthead_title: Elfriede Steil-Schächinger
minimal_mistakes_skin: "naturheilkunde"
footer:
  links:
    - label: Impressum
      url: /impressum
    - label: Datenschutz
      url: /datenschutz
    - label: "Kontakt & Anfahrt"
      url: /kontakt
atom_feed:
  hide: true
breadcrumbs: false
date_format: "%d.%m.%Y"
search: true

author: elfriede

defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: single
      author_profile: false
      share: false
  - scope:
      path: ""
      type: discourses
    values:
      layout: single
      author_profile: true
      share: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
      business_hours: true
  - scope:
      path: ""
      type: discourses
    values:
      layout: single
      classes: wide
      author_profile: true
      related: true
